import fs from 'node:fs';import assert from 'node:assert/strict';import pg from 'pg';import{randomUUID}from'node:crypto';
const cfg=JSON.parse(fs.readFileSync('.sites-runtime/postgres-test-env.json'));
if(cfg.TWAP_DB_SCHEMA!=='verification')throw Error('Only isolated verification schema is allowed');
const db=new pg.Client({connectionString:cfg.DATABASE_URL,options:'-c search_path=verification,public'});await db.connect();
const origin='http://localhost:3001';let checks=0;
async function api(path,payload,cookie,expected=200){const r=await fetch(origin+path,{method:payload?'POST':'GET',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{})},...(payload?{body:JSON.stringify(payload)}:{})});const d=await r.json();assert.equal(r.status,expected,`${path} ${payload?.action}: ${JSON.stringify(d)}`);checks++;return{d,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const owner=await api('/api/auth',{action:'login',email:cfg.TWAP_ADMIN_EMAIL,password:'IsolatedOwner#2026!'});assert.match(owner.d.redirect,/admin/);checks++;
const seed=randomUUID().slice(0,8),password='TestMember#2026!';
const a=await api('/api/auth',{action:'signup',name:'Verification A',email:`a-${seed}@example.test`,password},null,201);
const b=await api('/api/auth',{action:'signup',name:'Verification B',email:`b-${seed}@example.test`,password},null,201);
const acct=await api('/api/account',{action:'init'},a.cookie);
assert.equal(acct.d.profile.preferences.accent,'auto');checks++;
await api('/api/admin',null,a.cookie,403);
await api('/api/account',{action:'save',preferences:{theme:'light',accent:'auto',density:'compact',motion:'reduced'}},a.cookie);
const again=await api('/api/account',{action:'init'},a.cookie);assert.equal(again.d.profile.preferences.theme,'light');checks++;
const row=(await db.query('SELECT user_id,preferences FROM profiles WHERE email=$1',[`a-${seed}@example.test`])).rows[0];assert.equal(JSON.parse(row.preferences).density,'compact');checks++;
const botId='047f0cd1-f335-43f0-b775-cb478c82ea08',now=new Date().toISOString();
await db.query("INSERT INTO bots(id,name,pair,family,strategy_key,description,status,min_allocation_cents,created_by,created_at,updated_at) VALUES($1,'Continuation Strategy','BTC5m','Crypto Shares','crypto-shares.continuation.btc5m','','published',100000,'twap_owner',$2,$2) ON CONFLICT(id) DO NOTHING",[botId,now]);
await api('/api/continuation',{action:'deploy',mode:'live',lotCents:1000},a.cookie,428);
const paper=await api('/api/continuation',{action:'deploy',mode:'paper',lotCents:1000},a.cookie,201);
await api('/api/continuation',{action:'pause',runId:paper.d.id},b.cookie,404);
await api('/api/continuation',{action:'deploy',mode:'paper',lotCents:1000},a.cookie,409);
await db.query("UPDATE bots SET status='draft' WHERE id=$1",[botId]);
const retained=await api('/api/account',{action:'init'},a.cookie);assert(retained.d.bots.some(b=>b.id===botId));checks++;
const undisclosed=await api('/api/account',{action:'init'},b.cookie);assert(!undisclosed.d.bots.some(b=>b.id===botId));checks++;
await db.query("UPDATE bots SET status='published' WHERE id=$1",[botId]);
const fakeKey='01'.repeat(32),live=await api('/api/continuation',{action:'deploy',mode:'live',lotCents:1000,force:true,walletAddress:'0x'+'11'.repeat(20),walletKey:fakeKey},a.cookie,201);
const state=await api('/api/continuation',null,a.cookie);assert(!JSON.stringify(state.d).includes(fakeKey));assert(!JSON.stringify(state.d).includes('wallet_cipher'));checks+=2;
const stored=(await db.query('SELECT wallet_cipher FROM continuation_runs WHERE id=$1',[live.d.id])).rows[0];assert(stored.wallet_cipher&&!stored.wallet_cipher.includes(fakeKey));checks++;
const before=(await db.query('SELECT (SELECT count(*) FROM transactions) tx,(SELECT count(*) FROM holdings) holdings,(SELECT count(*) FROM deployments) deployments,(SELECT count(*) FROM portfolio_snapshots) snapshots')).rows[0];
const lease=randomUUID();
async function event(data,expected=200){if(data.action!=='heartbeat'){await event({action:'heartbeat',observedAt:Date.now(),priceE18:'1001',roundStart:Math.floor(Date.now()/300000)*300,openE18:'1000',message:''});if(data.action==='exit-prepare'){data.observedAt=Date.now();data.stableSince=Date.now()-5000;}}const r=await fetch(origin+'/api/continuation/runner',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+cfg.TWAP_BOT_RUNNER_TOKEN},body:JSON.stringify({...data,lease})});const d=await r.json();assert.equal(r.status,expected,JSON.stringify(d));checks++;return d;}
await api('/api/continuation/runner',null,a.cookie,401);
const start=Math.floor(Date.now()/300000)*300;
await event({action:'heartbeat',observedAt:Date.now(),priceE18:'1001',roundStart:start,openE18:'1000',message:''});
await api('/api/continuation',{action:'play',runId:paper.d.id},a.cookie);
await event({action:'claim',runId:paper.d.id,start:start-300,conditionId:'test',tokenId:'123',direction:'Up'},409);
const roundId=randomUUID();await db.query("INSERT INTO continuation_rounds(id,run_id,start_seconds,market_slug,condition_id,token_id,direction,stake_cents,status,created_at,updated_at) VALUES($1,$2,$3,'verification-only','test','123','Up',1000,'submitted',$4,$4)",[roundId,paper.d.id,start-600,now]);
const fill={action:'fill',roundId,costMicros:10000000,sharesMicros:19000000,feeMicros:300000};await event(fill);await event(fill);
let run=(await db.query('SELECT paper_cash_micros FROM continuation_runs WHERE id=$1',[paper.d.id])).rows[0];assert.equal(Number(run.paper_cash_micros),990000000);checks++;
await api('/api/continuation',{action:'pause',runId:paper.d.id},a.cookie);
await api('/api/continuation',{action:'configure',runId:paper.d.id,lotCents:2000},a.cookie,409);
await event({action:'resolve',roundId,winner:'Down'});await event({action:'resolve',roundId,winner:'Down'});
run=(await db.query('SELECT loss_streak FROM continuation_runs WHERE id=$1',[paper.d.id])).rows[0];assert.equal(Number(run.loss_streak),1);checks++;
await api('/api/continuation',{action:'configure',runId:paper.d.id,lotCents:1000},a.cookie);
const after=(await db.query('SELECT (SELECT count(*) FROM transactions) tx,(SELECT count(*) FROM holdings) holdings,(SELECT count(*) FROM deployments) deployments,(SELECT count(*) FROM portfolio_snapshots) snapshots')).rows[0];assert.deepEqual(after,before);checks++;
const round2=randomUUID();await db.query("INSERT INTO continuation_rounds(id,run_id,start_seconds,market_slug,condition_id,token_id,direction,stake_cents,status,cost_micros,shares_micros,created_at,updated_at) VALUES($1,$2,$3,'verification-only','test','123','Up',1000,'open',5000000,10000000,$4,$4)",[round2,paper.d.id,Math.floor(Date.now()/300000)*300,now]);
const exitId='paper-'+randomUUID();
await event({action:'exit-prepare',roundId:round2,orderId:exitId,sharesMicros:10000000,walletSharesMicros:10000000,stableSince:Date.now()-5000,observedAt:Date.now(),bidMicros:990000});
const sale={action:'exit-fill',roundId:round2,orderId:exitId,sharesMicros:10000000,grossMicros:9900000,feeMicros:6930,cashMicros:9893070};await event(sale);await event(sale);
const closed=(await db.query('SELECT * FROM continuation_rounds WHERE id=$1',[round2])).rows[0];assert.equal(closed.status,'won');assert.equal(Number(closed.pnl_micros),4893070);checks+=2;
const liveRound=randomUUID(), liveOrder='0x'+randomUUID().replaceAll('-','').repeat(2), liveTx='0x'+randomUUID().replaceAll('-','').repeat(2);
await db.query("INSERT INTO continuation_rounds(id,run_id,start_seconds,market_slug,condition_id,token_id,direction,stake_cents,status,cost_micros,shares_micros,created_at,updated_at) VALUES($1,$2,$3,'verification-only','test','123','Up',1000,'open',5000000,10000000,$4,$4)",[liveRound,live.d.id,Math.floor(Date.now()/300000)*300,now]);
await event({action:'exit-prepare',roundId:liveRound,orderId:liveOrder,sharesMicros:100000000,walletSharesMicros:100000000,stableSince:Date.now()-5000,observedAt:Date.now(),bidMicros:990000});
const fullSale={action:'exit-fill',roundId:liveRound,orderId:liveOrder,sharesMicros:100000000,grossMicros:99000000,feeMicros:69300,cashMicros:98930700,fills:[{id:liveTx+':1',orderId:liveOrder,side:'SELL',tokenId:'123',transactionHash:liveTx,logIndex:1,blockNumber:1234,grossMicros:99000000,sharesMicros:100000000,feeMicros:69300,cashMicros:98930700,price:'0.990000000000000000',tradeIds:['verification-trade']}]};
await event(fullSale);await event(fullSale);
const attributed=(await db.query('SELECT sale_proceeds_micros,sold_shares_micros,pnl_micros FROM continuation_rounds WHERE id=$1',[liveRound])).rows[0];
assert.equal(Number(attributed.sale_proceeds_micros),9893070);assert.equal(Number(attributed.sold_shares_micros),10000000);assert.equal(Number(attributed.pnl_micros),4893070);checks+=3;
const full=(await db.query('SELECT cash_micros,filled_shares_micros FROM continuation_orders WHERE id=$1',[liveOrder])).rows[0];assert.equal(Number(full.cash_micros),98930700);assert.equal(Number(full.filled_shares_micros),100000000);checks+=2;
console.log(`PostgreSQL HTTP verification: ${checks} checks passed.`);await db.end();
