import type { BotFamily } from "./bot-families";
export type Role = "user" | "admin" | "owner";
export type Profile = {
  userId: string;
  name: string;
  email: string;
  role: Role;
  status: string;
  referralCode: string;
  createdAt: string;
  lastLoginAt: string;
  preferences: Record<string, string>;
  authMethod: string;
};
export type BotRecord = {
  strategy_key: string | null;
  family: BotFamily | null;
  id: string;
  name: string;
  pair: string;
  description: string;
  status: string;
  min_allocation_cents: number;
  created_at: string;
  updated_at: string;
};
export type Deployment = {
  family: BotFamily | null;
  id: string;
  user_id: string;
  bot_id: string;
  name: string;
  pair: string;
  allocation_cents: number;
  status: string;
  note: string;
  created_at: string;
  updated_at: string;
  email?: string;
};
export type Transaction = {
  id: string;
  user_id: string;
  type: string;
  asset: string;
  quantity: string;
  amount_cents: number;
  balance_delta_cents: number;
  status: string;
  provider_ref: string | null;
  created_at: string;
  email?: string;
};
export type Holding = {
  id: string;
  symbol: string;
  name: string;
  quantity: string;
  value_cents: number | null;
  updated_at: string;
};
export type Snapshot = { value_cents: number; recorded_at: string };
export type PlatformSettings = {
  registrationsOpen: boolean;
  deploymentsOpen: boolean;
  referralsEnabled: boolean;
  maintenanceMode: boolean;
  announcement: string;
  supportEmail: string;
  referralTerms: string;
};
export type Account = {
  profile: Profile;
  sessionAccent: string;
  referrals: { created_at: string }[];
  referralCount: number;
  isNew: boolean;
  referralNotice?: string;
  holdings: Holding[];
  transactions: Transaction[];
  transactionCount: number;
  deployments: Deployment[];
  bots: BotRecord[];
  snapshots: Snapshot[];
  balanceCents: number;
  settings: PlatformSettings;
};
export type AdminUser = {
  user_id: string;
  display_name: string;
  email: string | null;
  role: Role;
  status: string;
  notes: string;
  auth_method: string;
  created_at: string;
  last_login_at: string;
  referral_code: string;
  referrals: number;
  deployments: number;
};
export type AdminData = {
  sessionAccent: string;
  view: string;
  rows: Record<string, unknown>[];
  total: number;
  page: number;
  pageSize: number;
  summary: Record<string, number>;
  settings: PlatformSettings;
  actor: Profile;
  integrations: { wallet: boolean; execution: boolean; email: boolean };
};
